# Generated by Django 3.1.1 on 2020-10-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=100)),
                ('n_bilhete', models.CharField(max_length=100)),
                ('idade', models.CharField(max_length=100)),
                ('tipo_credito', models.CharField(choices=[('Crédito Habitação', 'Crédito Habitação'), ('Pessoal', 'Pessoal')], default='Pessoal', max_length=100)),
                ('salario_mensal', models.CharField(max_length=100)),
                ('empreendedor', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=100)),
                ('ben_credito', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=100)),
                ('montate_credito', models.CharField(max_length=100)),
                ('qtd_mes_credito', models.CharField(max_length=100)),
                ('como_quer_pagar', models.CharField(choices=[('Por Prestações', 'Por Prestações'), ('Montante Completo', 'Montante Completo')], default='Por Prestações', max_length=100)),
                ('valor_mes_prestacao', models.CharField(max_length=100)),
            ],
        ),
    ]
