# Generated by Django 3.1.1 on 2020-10-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_clientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='n_bilhete',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='qtd_mes_credito',
        ),
        migrations.AddField(
            model_name='clientes',
            name='provincia',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], default='Masculino', max_length=100),
        ),
    ]
