# Generated by Django 3.1.1 on 2020-10-27 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20201027_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='ben_credito',
        ),
    ]
