# Generated by Django 3.1.1 on 2020-11-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_remove_clientes_ben_credito'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='estado_credito',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='financiamento',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='taxa_de_recuperação',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='total_rec_prncp',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='valor_financiamento',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
