# Generated by Django 3.1.1 on 2020-11-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20201113_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='recoveries',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
