# Generated by Django 3.1.1 on 2020-11-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_clientes_recoveries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='financiamento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='recoveries',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='total_rec_prncp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='valor_financiamento',
            field=models.IntegerField(),
        ),
    ]
